listen_addresses = '*'
port = 5432
ssl = on
password_encryption = 'scram-sha-256'
log_connections = on
log_disconnections = on
log_min_error_statement = error
shared_preload_libraries = 'pgaudit'
hba_file = 'pg_hba.conf'
ident_file = 'pg_ident.conf'
