name: Build and Release Fyne App

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Download deps
        run: go mod tidy

      - name: Build app (required before fyne package)
        run: go build -o app.exe ./cmd/app-gui

      - name: Package with Fyne (official way)
        run: fyne package -os windows -icon internal/assets/icon.png -app-id com.tulgu.bdscan

      - name: Rename output
        run: rename "BD Scan.exe" "bd-scan-windows.exe"

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: bd-scan-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
